// Code generated by go-swagger; DO NOT EDIT.

package recommend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new recommend API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for recommend API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
RecommendCluster provides a recommended set of node pools on a given provider in a specific region
*/
func (a *Client) RecommendCluster(params *RecommendClusterParams) (*RecommendClusterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRecommendClusterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "recommendCluster",
		Method:             "POST",
		PathPattern:        "/recommender/provider/{provider}/service/{service}/region/{region}/cluster",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RecommendClusterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RecommendClusterOK), nil

}

/*
RecommendClusterScaleOut provides a recommendation for a scale out based on a current cluster layout on a given provider in a specific region
*/
func (a *Client) RecommendClusterScaleOut(params *RecommendClusterScaleOutParams) (*RecommendClusterScaleOutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRecommendClusterScaleOutParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "recommendClusterScaleOut",
		Method:             "PUT",
		PathPattern:        "/recommender/provider/{provider}/service/{service}/region/{region}/cluster",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RecommendClusterScaleOutReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RecommendClusterScaleOutOK), nil

}

/*
RecommendMultiCluster provides a recommended set of node pools on a given provider in a specific region
*/
func (a *Client) RecommendMultiCluster(params *RecommendMultiClusterParams) (*RecommendMultiClusterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRecommendMultiClusterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "recommendMultiCluster",
		Method:             "POST",
		PathPattern:        "/recommender/multicloud",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RecommendMultiClusterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RecommendMultiClusterOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
