// Code generated by go-swagger; DO NOT EDIT.

package recommend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/banzaicloud/telescopes/pkg/recommender-client/models"
)

// NewRecommendClustersSetupParams creates a new RecommendClustersSetupParams object
// with the default values initialized.
func NewRecommendClustersSetupParams() *RecommendClustersSetupParams {
	var ()
	return &RecommendClustersSetupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRecommendClustersSetupParamsWithTimeout creates a new RecommendClustersSetupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRecommendClustersSetupParamsWithTimeout(timeout time.Duration) *RecommendClustersSetupParams {
	var ()
	return &RecommendClustersSetupParams{

		timeout: timeout,
	}
}

// NewRecommendClustersSetupParamsWithContext creates a new RecommendClustersSetupParams object
// with the default values initialized, and the ability to set a context for a request
func NewRecommendClustersSetupParamsWithContext(ctx context.Context) *RecommendClustersSetupParams {
	var ()
	return &RecommendClustersSetupParams{

		Context: ctx,
	}
}

// NewRecommendClustersSetupParamsWithHTTPClient creates a new RecommendClustersSetupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRecommendClustersSetupParamsWithHTTPClient(client *http.Client) *RecommendClustersSetupParams {
	var ()
	return &RecommendClustersSetupParams{
		HTTPClient: client,
	}
}

/*RecommendClustersSetupParams contains all the parameters to send to the API endpoint
for the recommend clusters setup operation typically these are written to a http.Request
*/
type RecommendClustersSetupParams struct {

	/*Request*/
	Request *models.Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the recommend clusters setup params
func (o *RecommendClustersSetupParams) WithTimeout(timeout time.Duration) *RecommendClustersSetupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recommend clusters setup params
func (o *RecommendClustersSetupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recommend clusters setup params
func (o *RecommendClustersSetupParams) WithContext(ctx context.Context) *RecommendClustersSetupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recommend clusters setup params
func (o *RecommendClustersSetupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recommend clusters setup params
func (o *RecommendClustersSetupParams) WithHTTPClient(client *http.Client) *RecommendClustersSetupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recommend clusters setup params
func (o *RecommendClustersSetupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the recommend clusters setup params
func (o *RecommendClustersSetupParams) WithRequest(request *models.Request) *RecommendClustersSetupParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the recommend clusters setup params
func (o *RecommendClustersSetupParams) SetRequest(request *models.Request) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *RecommendClustersSetupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
