// Code generated by go-swagger; DO NOT EDIT.

package recommend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new recommend API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for recommend API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
RecommendClusterScaleOut provides a recommendation for a scale out based on a current cluster layout on a given provider in a specific region
*/
func (a *Client) RecommendClusterScaleOut(params *RecommendClusterScaleOutParams) (*RecommendClusterScaleOutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRecommendClusterScaleOutParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "recommendClusterScaleOut",
		Method:             "PUT",
		PathPattern:        "/recommender/{provider}/{service}/{region}/cluster",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RecommendClusterScaleOutReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RecommendClusterScaleOutOK), nil

}

/*
RecommendClusterSetup provides a recommended set of node pools on a given provider in a specific region
*/
func (a *Client) RecommendClusterSetup(params *RecommendClusterSetupParams) (*RecommendClusterSetupOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRecommendClusterSetupParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "recommendClusterSetup",
		Method:             "POST",
		PathPattern:        "/recommender/{provider}/{service}/{region}/cluster",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RecommendClusterSetupReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RecommendClusterSetupOK), nil

}

/*
RecommendClustersSetup provides a recommended set of node pools on a given provider in a specific region
*/
func (a *Client) RecommendClustersSetup(params *RecommendClustersSetupParams) (*RecommendClustersSetupOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRecommendClustersSetupParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "recommendClustersSetup",
		Method:             "POST",
		PathPattern:        "/recommender/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RecommendClustersSetupReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RecommendClustersSetupOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
