run:
    skip-dirs:
        - .gen
        - client

linters-settings:
    revive:
        confidence: 0.9

    gocyclo:
        min-complexity: 20

    lll:
        line-length: 200

    goimports:
        local-prefixes: github.com/sagikazarmark/modern-go-application

# settings copied from https://github.com/banzaicloud/pipeline/blob/update-chart/.golangci.yml
linters:
    enable-all: true
    disable:
        - funlen
        - maligned
        - wsl
        - gomnd
        - godot

        # TODO: fixme
        - gosec
        - megacheck
        - varcheck

        # Disable govet for now because it fails on Circle
        - govet

        # TODO: fixme
        - nestif
        - exhaustive
        - nlreturn
        - noctx

        - goerr113
        - bodyclose
        - dupl
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godox
        - interfacer
        - lll
        - nakedret
        - prealloc
        - scopelint
        - stylecheck
        - testpackage
        - unparam

        # Introduced with 1.50.0 since 1.30.0 (https://github.com/golangci/golangci-lint/blob/bac47a7e52a1dcd91fc7d3e33af2686e22cc9e0f/CHANGELOG.md)
        # TODO: enable them one by one to test and configure
        - asasalint
        - bidichk
        - contextcheck
        - containedctx
        - cyclop
        - decorder
        - dupword
        - durationcheck
        - errchkjson
        - errname
        - errorlint
        - execinquery
        - exhaustivestruct
        - exhaustruct
        - forbidigo
        - forcetypeassert
        - gomoddirectives
        - grouper
        - ifshort
        - importas
        - interfacebloat
        - ireturn
        - logrlint
        - maintidx
        - makezero
        - nilerr
        - nilnil
        - nolintlint
        - nonamedreturns
        - nosnakecase
        - nosprintfhostport
        - paralleltest
        - predeclared
        - promlinter
        - reassign
        - tagliatelle
        - tenv
        - testableexamples
        - thelper
        - tparallel
        - usestdlibvars
        - varnamelen
        - wastedassign
        - wrapcheck

        # incompatible with goimports
        - gci

        # deprecated (since v1.41.0), replaced by revive
        - golint
        # deprecated (since v1.49.0), replaced by unused
        - deadcode
        - structcheck

    fast: false

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
