apiVersion: v1
kind: Service
metadata:
  name: telescopes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telescopes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: null
  selector:
    {{- include "telescopes.selectorLabels" . | nindent 4 }}
