// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ClusterRecommendationAccuracy ClusterRecommendationAccuracy encapsulates recommendation accuracy
// swagger:model ClusterRecommendationAccuracy
type ClusterRecommendationAccuracy struct {

	// Number of recommended cpus
	RecCPU float64 `json:"cpu,omitempty"`

	// The summarised amount of memory in the recommended cluster
	RecMem float64 `json:"memory,omitempty"`

	// Number of recommended nodes
	RecNodes int64 `json:"nodes,omitempty"`

	// Number of regular instance type in the recommended cluster
	RecRegularNodes int64 `json:"regularNodes,omitempty"`

	// Amount of regular instance type prices in the recommended cluster
	RecRegularPrice float64 `json:"regularPrice,omitempty"`

	// Number of spot instance type in the recommended cluster
	RecSpotNodes int64 `json:"spotNodes,omitempty"`

	// Amount of spot instance type prices in the recommended cluster
	RecSpotPrice float64 `json:"spotPrice,omitempty"`

	// Total price in the recommended cluster
	RecTotalPrice float64 `json:"totalPrice,omitempty"`

	// Availability zones in the recommendation
	RecZone []string `json:"zone"`
}

// Validate validates this cluster recommendation accuracy
func (m *ClusterRecommendationAccuracy) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterRecommendationAccuracy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterRecommendationAccuracy) UnmarshalBinary(b []byte) error {
	var res ClusterRecommendationAccuracy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
