// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Engine Engine represents the recommendation engine, it operates on a map of provider -> VmRegistry
// swagger:model Engine
type Engine interface{}
