// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MultiClusterRecommendationReq MultiClusterRecommendationReq encapsulates the recommendation input data
// swagger:model MultiClusterRecommendationReq
type MultiClusterRecommendationReq struct {

	// continents
	Continents []string `json:"continents"`

	// providers
	Providers []*Provider `json:"providers"`

	// Maximum number of response per service
	RespPerService int64 `json:"respPerService,omitempty"`

	// cluster recommendation req
	ClusterRecommendationReq *ClusterRecommendationReq `json:"clusterRecommendationReq,omitempty"`
}

// Validate validates this multi cluster recommendation req
func (m *MultiClusterRecommendationReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProviders(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterRecommendationReq(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MultiClusterRecommendationReq) validateProviders(formats strfmt.Registry) error {

	if swag.IsZero(m.Providers) { // not required
		return nil
	}

	for i := 0; i < len(m.Providers); i++ {
		if swag.IsZero(m.Providers[i]) { // not required
			continue
		}

		if m.Providers[i] != nil {
			if err := m.Providers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MultiClusterRecommendationReq) validateClusterRecommendationReq(formats strfmt.Registry) error {

	if swag.IsZero(m.ClusterRecommendationReq) { // not required
		return nil
	}

	if m.ClusterRecommendationReq != nil {
		if err := m.ClusterRecommendationReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clusterRecommendationReq")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MultiClusterRecommendationReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MultiClusterRecommendationReq) UnmarshalBinary(b []byte) error {
	var res MultiClusterRecommendationReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
