// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// NodePoolDesc node pool desc
// swagger:model NodePoolDesc
type NodePoolDesc struct {

	// Instance type of VMs in the node pool
	InstanceType string `json:"instanceType,omitempty"`

	// Number of VMs in the node pool
	SumNodes int64 `json:"sumNodes,omitempty"`

	// Signals that the node pool consists of regular or spot/preemptible instance types
	VMClass string `json:"vmClass,omitempty"`
}

// Validate validates this node pool desc
func (m *NodePoolDesc) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodePoolDesc) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodePoolDesc) UnmarshalBinary(b []byte) error {
	var res NodePoolDesc
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
