// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SingleClusterRecommendationReq SingleClusterRecommendationReq encapsulates the recommendation input data
// swagger:model SingleClusterRecommendationReq
type SingleClusterRecommendationReq struct {

	// Are burst instances allowed in recommendation
	AllowBurst bool `json:"allowBurst,omitempty"`

	// AllowOlderGen allow older generations of virtual machines (applies for EC2 only)
	AllowOlderGen bool `json:"allowOlderGen,omitempty"`

	// Category specifies the virtual machine category
	Category []string `json:"category"`

	// Excludes is a blacklist - a slice with vm types to be excluded from the recommendation
	Excludes []string `json:"excludes"`

	// Includes is a whitelist - a slice with vm types to be contained in the recommendation
	Includes []string `json:"includes"`

	// Maximum number of nodes in the recommended cluster
	MaxNodes int64 `json:"maxNodes,omitempty"`

	// Minimum number of nodes in the recommended cluster
	MinNodes int64 `json:"minNodes,omitempty"`

	// NetworkPerf specifies the network performance category
	NetworkPerf []string `json:"networkPerf"`

	// Percentage of regular (on-demand) nodes in the recommended cluster
	OnDemandPct int64 `json:"onDemandPct,omitempty"`

	// If true, recommended instance types will have a similar size
	SameSize bool `json:"sameSize,omitempty"`

	// Total number of CPUs requested for the cluster
	SumCPU float64 `json:"sumCpu,omitempty"`

	// Total number of GPUs requested for the cluster
	SumGpu int64 `json:"sumGpu,omitempty"`

	// Total memory requested for the cluster (GB)
	SumMem float64 `json:"sumMem,omitempty"`

	// Availability zone that the cluster should expand to
	Zone string `json:"zone,omitempty"`
}

// Validate validates this single cluster recommendation req
func (m *SingleClusterRecommendationReq) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SingleClusterRecommendationReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SingleClusterRecommendationReq) UnmarshalBinary(b []byte) error {
	var res SingleClusterRecommendationReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
